### ISSUE TITLE
search by block

### ISSUE THREAD

**Issue by majshehab** [CityOfPhiladelphia/property2#57]
when users type in "1200-1299 market" as told to do so in the example, they only get the even # properties on said block

**Comment by gsf** [comment]
Yeah, at the block endpoint the API hits both "1200-1298 market" and "1201-1299 market":
http://api.phila.gov/opa/v1.1/block/1234%20market/?format=json

I'm not happy about exposing the address span search at all. Aside from this issue, it's too easy to break the API with a query like "100-1200 walnut". Feels like a lower level of interaction than should be advertised to the user.

I see four possible solutions:
1. Change the API so that 1200-1299 returns all addresses for the block. Given that even the block endpoint appears to work around this limit, I'm guessing that would mean updating whatever API the OPA API is hitting here.
2. Parse the search query. This is possible but tricky and with a lot of edge cases.
3. Explain this in some kind of help text, which would probably necessitate some kind of "power search help" section. Ugh.
4. Expose a query that hits the block endpoint. My favorite option. We already have #24 to do this on the property page. Is there a way to do this in the search that doesn't clash with our current UX?

**Comment by majshehab** [comment]
1 or 2 for now.... 4 for later.  3 never.

**Comment by atogle** [comment]
What about a checkbox that says "Search the whole block" or something similar?

We could also add a similar button to a property details -- "See all properties on this block"

**Comment by atogle** [comment]
Included in the new search options.

![screenshot 2015-09-17 13 16 46](https://cloud.githubusercontent.com/assets/446930/9940527/6595f780-5d3e-11e5-8a22-9b22844d5f07.png)
